## Numpy review

In [1]:
import numpy as np

In [2]:
# 1d array:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 2d array:
np.array([(1,2,3,4,5,6,7,8,9), (9,8,7,6,5,4,3,2,1)])

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [6]:
# Creating an array using a list
num = [1, 2, 3, 4, 5]
np.array(num)

array([1, 2, 3, 4, 5])

## Generating arrays

With numpy, we have several options of generating an array such as:
 1. Identity array
 2. Array full of zeros
 3. Generating an array in a given range
 4. Generating an array with a given size
 5. Random values array
 

In [7]:
# Identity array
identity = np.identity(6)
print(identity)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [8]:
# Array full of zeros
print(np.zeros(9))

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
# 2d array of zeros
print(np.zeros((9, 9)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
# We can also do it with ones
print(np.ones((9, 5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
# Array in a given range
np.arange(0, 9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

##### in the above case, the range uses a closed interval to the left
##### and an open interval to the right np.arange(x, y) will
##### produce an array [x,y[

In [20]:
# It is also possible to linspace an array
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [21]:
# Random arrays
np.random.rand(4, 5)

array([[0.6102908 , 0.06912946, 0.28298765, 0.82705381, 0.62752419],
       [0.37683718, 0.42756399, 0.71449017, 0.18349644, 0.61514556],
       [0.88890417, 0.08062049, 0.24458709, 0.84935621, 0.32379807],
       [0.02431214, 0.48648068, 0.20888687, 0.93599226, 0.14500271]])

In [22]:
# Generate one random integer in a given range
np.random.randint(5, 6)

5

## Array indexing and selection

In [29]:
array_1d = np.array([1,2,3,4,5,6,7,8,9])

In [30]:
array_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
array_1d[3]

4

In [32]:
array_1d[-1]

9

In [33]:
array_1d[2:5]

array([3, 4, 5])

## 2d array

In [36]:
array_2d = np.array([(1,2,3,4,7,8,9), (9,8,7,6,3,2,1), (4,3,2,5,7,8,9)])

In [37]:
array_2d

array([[1, 2, 3, 4, 7, 8, 9],
       [9, 8, 7, 6, 3, 2, 1],
       [4, 3, 2, 5, 7, 8, 9]])

In [40]:
# array[row][column]
array_2d[1][2]

7

In [41]:
array_2d[0]

array([1, 2, 3, 4, 7, 8, 9])

In [53]:
# Selection a group of elements
array_2d[:2]

array([[1, 2, 3, 4, 7, 8, 9],
       [9, 8, 7, 6, 3, 2, 1]])

In [46]:
array_2d

array([[1, 2, 3, 4, 7, 8, 9],
       [9, 8, 7, 6, 3, 2, 1],
       [4, 3, 2, 5, 7, 8, 9]])

In [51]:
# Return the first row
array_2d[0,:]

array([1, 2, 3, 4, 7, 8, 9])

## Condicionals

In [55]:
arr= np.array(([1,2,3],[4,5,6],[7,8,9]))

# Select all elements that are less than 3

arr[arr<3]

array([1, 2])

In [56]:
# Select all elements that are odd

arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

In [57]:
# Multiple conditions
arr[(arr % 2 == 0) & (arr > 4)]

array([6, 8])