In [2]:
import numpy as np

array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Standard deviation

In [12]:
np.std(array)

2.8722813232690143

In [8]:
array2 = np.random.rand(3, 3)
array2

array([[0.29950618, 0.25615851, 0.55252431],
       [0.94222752, 0.16051461, 0.21894915],
       [0.70722203, 0.96744343, 0.29880451]])

In [9]:
np.std(array2)

0.2968550675795927

In [11]:
np.std(array2, axis = 1)

array([0.13069468, 0.3555311 , 0.27519651])

## Variance

In [13]:
np.var(array2)

0.08812293114768455

In [15]:
np.var(array)

8.25

In [17]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.var(arr)

0.0

## Mean

In [19]:
np.mean(array2)

0.48926113856488773

In [20]:
np.mean(arr)

1.0

## Median

In [22]:
np.median(array2)

0.2995061782367324

In [23]:
np.median(arr)

1.0

## Data manipulation

In [25]:
# Shape of an array
arr1 = np.arange(0,10)
arr2 = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [26]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.shape(arr1)

(10,)

In [29]:
np.shape(arr2)

(3, 3)

In [30]:
arr2.shape

(3, 3)

## Shaping an array

In [35]:
np.reshape(arr1, newshape=(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [36]:
# It is important that the rows and columns of the new shape needs to
# comform the data of the current array

## Copying array

In [39]:
array3 = array2.copy()
array3

array([[0.29950618, 0.25615851, 0.55252431],
       [0.94222752, 0.16051461, 0.21894915],
       [0.70722203, 0.96744343, 0.29880451]])

In [40]:
# Note for myself: i think that if i copy it like: array3 = array2
# it will only copy the pointer to array2 instead of copy it's data

## Joining arrays

In [53]:
array4 = np.random.rand(3, 3)
array_union = np.concatenate((array2, array4))

In [54]:
array_union

array([[0.29950618, 0.25615851, 0.55252431],
       [0.94222752, 0.16051461, 0.21894915],
       [0.70722203, 0.96744343, 0.29880451],
       [0.5204335 , 0.72400758, 0.16592352],
       [0.11431606, 0.69226827, 0.79808938],
       [0.15977465, 0.57863054, 0.91272559]])

## Spliting arrays

In [57]:
np.split(array_union, 2)

[array([[0.29950618, 0.25615851, 0.55252431],
        [0.94222752, 0.16051461, 0.21894915],
        [0.70722203, 0.96744343, 0.29880451]]),
 array([[0.5204335 , 0.72400758, 0.16592352],
        [0.11431606, 0.69226827, 0.79808938],
        [0.15977465, 0.57863054, 0.91272559]])]

## Adding and reapeting elements in an array

In [58]:
arr = np.arange(0,6)
arr

array([0, 1, 2, 3, 4, 5])

In [59]:
# Adding values to the end of an array
np.append(arr, 6)


array([0, 1, 2, 3, 4, 5, 6])

In [60]:
np.tile(arr,5)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3,
       4, 5, 0, 1, 2, 3, 4, 5])

In [61]:
np.repeat(arr, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## Sorting an array

In [72]:
arr = np.array([[1,2,3,4,5,3,2,1,3,5,6,7,7,5,9,5]])

arr

array([[1, 2, 3, 4, 5, 3, 2, 1, 3, 5, 6, 7, 7, 5, 9, 5]])

In [73]:
np.sort(arr)

array([[1, 1, 2, 2, 3, 3, 3, 4, 5, 5, 5, 5, 6, 7, 7, 9]])

In [74]:
# Finding unique elements in an array
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 9])

## Reversing an array

In [78]:
arr = np.array([[1,2,3], [3,2,1], [2,1,3]])
arr

array([[1, 2, 3],
       [3, 2, 1],
       [2, 1, 3]])

In [80]:
# flip it upside down
np.flipud(arr)

array([[2, 1, 3],
       [3, 2, 1],
       [1, 2, 3]])

In [81]:
# flip it left to right
np.fliplr(arr)

array([[3, 2, 1],
       [1, 2, 3],
       [3, 1, 2]])